apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: cart-config
  namespace: dev-pedjeab-cart
  envs:
  - ./cart-config/cart-config.env

generatorOptions:
  disableNameSuffixHash: true

