apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: cart-config
  namespace: argocd
  envs:
  - ./cart-config/cart-config.env

generatorOptions:
  disableNameSuffixHash: true
resources:
  - pre-sync-job.yaml